### ISSUE TITLE
Error loading SVG file

### ISSUE THREAD

**Issue by T-bond** [Maddoc42/Android-Material-Icon-Generator#12]
Hello.

I'm trying to load my SVG file, but I got js error in the Developer Console.

`index.js:9 Uncaught TypeError: Cannot read property '_intersection' of null`
(Google Chrome 52.0.2743.116 m (64-bit))

In Microsoft Edge:
The following popup appears:

> Invalid SVG file
> Please use a real SVG file instead.

My [SVG file](https://drive.google.com/open?id=0Bwvod2purLX6UWRCXzMyWHlHOG8)
It is a minified, simplified version of the svg made in Inkscape. (None of the option worked by default during export from Inkscape)
Simplified by: https://jakearchibald.github.io/svgomg/

I tried the example svg-s from this repo, and tried to edit the path, but it gives the same error.
There is a problem with the svg or with the generator?

**Comment by Maddoc42** [comment]
Hey @T-bond, thanks for reporting this issue.

The icon you are trying to convert contains two open paths with a large stroke width, which makes up the roof and walls. The shadow generator only works with closed paths.

Inkscape has a cool little tool for exactly that purpose. If you select your path, go to "Path" -> "Stroke to Path" and the result will be two closed paths. That should work fine with the shadow generator.

To illustrate what I mean:

Original icon (open paths)
![house1](https://cloud.githubusercontent.com/assets/1794729/18087753/008bb0e2-6eb7-11e6-9d16-3ea30dc14181.png)

Updated icon (closed paths)
![house2](https://cloud.githubusercontent.com/assets/1794729/18087824/63cb2a7a-6eb7-11e6-83bd-01ad111de001.png)

Final result
![ic_launcher](https://cloud.githubusercontent.com/assets/1794729/18087857/8ead1924-6eb7-11e6-98b8-6caed0163e6f.png)

Does that makes sense?

**Comment by Maddoc42** [comment]
On a second thought, that should probably be included as part of a FAQ. Do you mind if I take your house icon as an example?

**Comment by T-bond** [comment]
Thanks. It worked.
You can use the icon as an example. :)
But the Chrome should show the same popup, or not?

**Comment by Maddoc42** [comment]
Yes, nice catch :flushed: Chrome doesn't display anything at all (other than console), that's a :beetle:!

**Comment by Maddoc42** [comment]
The generator now shows a custom error msg on open paths, c10a714 should fix that.

Thanks again @T-bond for finding this :blush:
