### ISSUE TITLE
Add option to apply 'Score' effect

### ISSUE THREAD

**Issue by ok3141** [Maddoc42/Android-Material-Icon-Generator#15]
Quote from [guide](https://material.google.com/style/icons.html#icons-product-icons):

> Scored material elements have the illusion of depth without losing their geometric form. Scores should be centered on symmetrical shapes.

Examples:

<img src="https://material-design.storage.googleapis.com/publish/material_v_9/0Bx4BSt6jniD7REh5NnRCWUFkYVU/style_logos_product_patterns_score_do.png" width="128">

<img src="https://lh3.googleusercontent.com/VzjqfHuZcFItnNxy65DHB3E0jR6_WqdOkaEA8NP4gRqySAZjbNf2nE4qxNfoKJSkBNMa=w128" width="96">

<img src="https://lh3.googleusercontent.com/5-zpxQHVo8YfuavTJkqL0U35VPqbt4vddb7OKedrSX8AlyDhBqx6NFFd7WwZDUUf3Ic=w128" width="96">

**Comment by Maddoc42** [comment]
Nice idea, this is really cool! :sunglasses: 

Displaying the background in two colors around a axis should be fairly straight forward. The icon might be little harder. Maybe start with background only first?

Really like this idea though, looks awesome :+1:

**Comment by ok3141** [comment]
Background is more than enough. With an option to change angle, like 0°, 45°, 90°, 135°.

I want to make it by myself, but I'm not familiar with language and tools you use for this project. Anyway I will try :)

**Comment by Maddoc42** [comment]
Really cool :+1: if I can help you with anything, please let me know! :)

**Comment by Maddoc42** [comment]
Score effects are coming :tada: :rocket: 

@shomeser I image you long ago found an alternative solution, but does this address your original request? Support for turning the score effect will come later :wink: 

![score](https://cloud.githubusercontent.com/assets/1794729/22075853/ed990ce4-ddad-11e6-991e-5ff14ebfe271.png)

**Comment by ok3141** [comment]
That's cool! Thank you! =)
