### ISSUE TITLE
Can i import and use a coloured SVG file?

### ISSUE THREAD

**Issue by CosimoSguanci** [Maddoc42/Android-Material-Icon-Generator#21]
The tools makes it monocolour, even in it's coloured.

**Comment by Maddoc42** [comment]
Hey @CosimoSguanci, thanks for reaching out. Unfortunately not at the moment, but that would be an interesting feature! :rocket:

**Comment by Maddoc42** [comment]
Hey @CosimoSguanci! Great news, color icons are now supported! Let me know if this works for you :)

![icon](https://cloud.githubusercontent.com/assets/1794729/22022558/cc85c89e-dcc2-11e6-96bb-3861e05d7667.png)

**Comment by Maddoc42** [comment]
Closing as resolved. @CosimoSguanci feel free to open back up if something it not working :)
