### ISSUE TITLE
using SVGs from illustrator

### ISSUE THREAD

**Issue by 3llomi** [Maddoc42/Android-Material-Icon-Generator#22]
can i save my icon as SVG using illustrator and then use it in Material icon ?

**Comment by Maddoc42** [comment]
Hey @3llomi! Sure, I don't see why not. Have you tried it?

**Comment by 3llomi** [comment]
yes i already tried it, saved from illustrator as SVG and upload it to Material Icon and the loading icon still spinning with (Uncaught Error: TypeError: Cannot read property 'getLength' of null) error in console.
however i figured it with a workaround by saving the icon as AI extension then upload it to CloudConvert website to convert it to SVG and finally upload it to Material Icon.
is there any direct way or the problem is in my icon?

**Comment by Maddoc42** [comment]
Not entirely sure. That error most likely stems from the underlying paper.js library, which unfortunately still has a couple of bugs when it comes to boolean operations.

Would you mind uploading your icon here, or if that is not possible, a "minimal" example which produces this error?

**Comment by 3llomi** [comment]
ok, can i send it to you privately?

**Comment by Maddoc42** [comment]
Sure! There should be an email address in my profile, feel free to send it to that.

**Comment by 3llomi** [comment]
ok it has been sent to you

**Comment by Maddoc42** [comment]
Cheers, thanks! :+1:

I have made some changes, icon seems to process fine now. Let me know if this works for you! 😊

**Comment by 3llomi** [comment]
that's great, it's working for me now
Thanks for support

**Comment by Maddoc42** [comment]
Awesome, thank's for reporting this :)
