### ISSUE TITLE
Licensing Contradiction

### ISSUE THREAD

**Issue by frhun** [Maddoc42/Android-Material-Icon-Generator#27]
The non-commercial exception to the AGPL is effectively without effect as the program can be acquired under the terms of the AGPL which permits to remove such "further restrictions". (see Section 7 and 10)

This is specifically stated in the official FSF FAQ: https://www.gnu.org/licenses/gpl-faq.html#GPLCommercially

**Comment by Maddoc42** [comment]
Thanks for pointing this out! This is an interesting observation. I am no expert on OSS Licenses, but from my understanding the software itself is available under the AGPL, while the icons generated with this tool (not code, hence independent of AGPL?) can be licensed differently. Of course this is just a superficial 'protection' as everybody is free to copy and host the software themselves.

Any holes in that logic?

**Comment by frhun** [comment]
Just to be clear you can't add restrictions to the output of that program if someone else hosted that program while he used it. (just my interpretation on that, but this seems to be similar to that: https://www.gnu.org/licenses/gpl-faq.html#RequireCitation)

But I'm pretty sure there's nothing preventing you from placing such restrictions on anyone using your server to generate that output, - this is of course purely theoretical, as you have to count on the honesty and kindness of people anyway

Maybe just let people know it would be nice of them to appreciate your work if they made money of it in some way or the other (maybe at the top of the README ), and make the LICENSE-non-commercial.md the LICENSE.md - I assume no one who would have paid before would stop because of that

**Comment by Maddoc42** [comment]
> Just to be clear you can't add restrictions to the output of that program if someone else hosted that program while he used it.

Agreed

> this is of course purely theoretical, as you have to count on the honesty and kindness of people anyway

Also agreed. If this is useful for somebody and they have a genuine idea of how to make a profit of it they are more than welcome to do so 👍 

Thanks for thinking this over! I'll close this for now as there is no immediate action required as far as I can see, feel free to open / append additional comments though.
