### ISSUE TITLE
File does not have a extension

### ISSUE THREAD

**Issue by ericswpark** [Maddoc42/Android-Material-Icon-Generator#6]
I do not know what the file's extension is - which means I cannot open it. I have tried .png, .ico, .svg, and even .jpg for crying out loud.

Which means I can't even use it.

**Comment by Maddoc42** [comment]
Which files are you referring to? The files in the zip all have proper extensions. The input file picker only accepts valid .svg files.

**Comment by ericswpark** [comment]
I'm referring to the actual finished image. And I've picked from the built
in Google icons in the website.

Actually, I've seen it now. The file is actually a zip. Maybe your script
could append that as well?

Thanks, issue resolved, please close this.
2016. 3. 21. 오전 1:10에 "Philipp Eichhorn" notifications@github.com님이 작성:

Which files are you referring to? The files in the zip all have proper

**Comment by Maddoc42** [comment]
What do you mean by append that as well? The downloaded file should have a .zip extension. If not then that's a bug. What browser are you using?

**Comment by ericswpark** [comment]
Using Chrome. File did not have extension, last two times I checked. OS was
Windows 10, and I had show file extension checked in Windows Explorer.
2016. 3. 21. 오후 6:24에 "Philipp Eichhorn" notifications@github.com님이 작성:

**Comment by Maddoc42** [comment]
You were right. The site indeed does not specify how the downloaded file should be called, however some versions of Chrome are smart enough to automatically add a .zip to the file. Thanks for mentioning that!

382534c86fc22d3483c73f70fb9075852024f13a should fix that. Changes are live. Please let me know if you are still having trouble moving forward.
